In [1]:
import numpy as np

# numpy 创建ndarray的方式

- np.array 从python的列表创建
- np.zeros np.empty np.ones 从零开始创建列表


In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
# 显示指定数组的数据类型

np.array([1, 2, 3, 4, 5, 6], dtype=np.float32)

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [4]:
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3, 5), dtype=np.float64)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.arange(0, 20, 2, dtype=np.int32)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [8]:
np.random.random((3, 3))

array([[0.78220644, 0.95387909, 0.86361072],
       [0.50684219, 0.21918232, 0.6086658 ],
       [0.76703682, 0.69777555, 0.8825596 ]])

In [9]:
# 正太分布
np.random.normal(0, 1, (100,))

array([ 2.43098693, -0.0295464 ,  1.8039694 ,  2.17589967,  1.34276729,
       -1.41127722, -1.30471581, -0.73798249,  0.90154318,  2.0802134 ,
        0.60531477,  1.14562833,  1.99718062,  0.64733367,  0.54893707,
       -0.4952209 ,  0.26135477,  0.99454865,  1.15778093,  0.68437981,
        1.28549221,  1.07881706, -1.67638638, -1.34490826, -0.5510273 ,
       -0.77826679,  1.49188159,  1.64404851,  0.98770164, -0.38555743,
       -1.20087857, -1.27197084,  0.15573252,  1.14134141,  0.23505274,
        1.0095826 ,  0.64563545,  1.02039722,  0.02292653, -0.45279123,
       -1.50611662, -1.0876785 ,  1.1215282 ,  1.00507047, -0.91380514,
        0.54242981,  1.38358474,  1.31576436,  1.08143777,  0.27884462,
       -0.57674977, -0.28805952,  0.39481293, -2.77460608,  0.98631506,
        0.23254726,  2.23083819, -2.14027538, -0.36030772, -0.55590874,
       -0.97700989, -0.06261438, -1.38912264, -0.11871997,  0.0301972 ,
        1.26598748,  0.57466313,  0.87568448, -0.53800894,  0.87

In [10]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.empty((2, 1))

array([[ 6.04487664e-69],
       [-4.01495755e-93]])

# numpy的数据类型

```
bool_
int_
intc  c语言的int类型
intp  integer for索引
int8
int16
int32
int64
uint8  uint16 uint32 uint64

float_  same as float64
float16 float32 float64

complex_   complex64 complex128

```