In [1]:
import numpy as np

# numpy 创建ndarray的方式

- np.array 从python的列表创建
- np.zeros np.empty np.ones 从零开始创建列表


In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
# 显示指定数组的数据类型

np.array([1, 2, 3, 4, 5, 6], dtype=np.float32)

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [4]:
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3, 5), dtype=np.float64)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.arange(0, 20, 2, dtype=np.int32)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [8]:
np.random.random((3, 3))

array([[0.06515931, 0.16806561, 0.08237602],
       [0.89101621, 0.6833174 , 0.35042541],
       [0.81933047, 0.85634148, 0.39342466]])

In [9]:
# 正态分布
np.random.normal(0, 1, (100,))

array([ 1.36532292e-01,  1.74331925e+00, -2.62481671e-01,  9.67979013e-01,
        8.12295728e-01,  4.04369377e-01,  2.42182986e+00, -1.67371937e+00,
        2.07492926e+00, -1.88594453e+00, -3.51807310e-01,  3.44392718e-01,
       -1.48486298e+00,  2.87960686e-01,  1.92310738e+00,  2.52367352e-01,
        6.93099869e-01,  1.05681134e+00,  1.08142656e+00,  2.12758409e-01,
        5.05402680e-01,  2.32870482e+00,  9.10933321e-01, -1.55605286e+00,
        4.78888998e-01, -1.68745712e-01, -4.05145513e-01,  2.33677972e-01,
       -1.62299687e+00,  1.50272204e+00, -3.16823197e-01,  1.10762391e+00,
       -9.28610048e-01, -5.68825345e-01, -4.53228145e-01,  1.30756526e-01,
        6.35596646e-01, -3.25553921e-01, -9.03160595e-01, -2.20679042e+00,
       -1.62433186e+00,  7.49864358e-01, -1.31584512e+00, -1.60381575e-01,
        1.48888444e+00, -3.89998842e-01,  4.69828248e-01,  4.69585980e-01,
       -8.43227541e-01,  4.46360923e-01,  2.31129743e+00,  6.05136032e-01,
        1.52194841e-01,  

In [10]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.empty((2, 1))

array([[-5.35546682e+022],
       [-2.80415985e-136]])

# numpy的数据类型

```
bool_
int_
intc  c语言的int类型
intp  integer for索引
int8
int16
int32
int64
uint8  uint16 uint32 uint64

float_  same as float64
float16 float32 float64

complex_   complex64 complex128

```

other things...