In [1]:
import numpy as np

np.random.seed(12345)
import matplotlib.pyplot as plt

plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [3]:
# %timeit my_arr2 = my_arr * 2
# %timeit my_list2 = [x * 2 for x in my_list]


In [4]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10


array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
# 查看数据的维度和类型

print(data.shape)
print(data.dtype)
print(data.ndim)


(2, 3)
float64
2


# 创建ndarray数组的方式

## np.array

## 创建空数组

`np.zeros`

`np.ones`

`np.empty`

## 创建序列

`np.arange`

## 其他的创建方式

![numpy数组创建方式](./img/img1.png "numpy数组的创建方式")

![numpy数组创建方式](./img/img2.png "numpy数组的创建方式")


In [8]:
np.zeros(10)
np.zeros((3, 6))
np.empty((2, 3, 2))

array([[[1.6021e-311, 2.4703e-322],
        [0.0000e+000, 0.0000e+000],
        [8.3444e-308, 1.3366e+160]],

       [[7.1194e-091, 3.1129e-032],
        [2.8295e-033, 1.9197e-052],
        [3.9991e+252, 4.9343e+257]]])

# ndarray 的数据类型

![ndarray的数据类型](./img/img3.png "ndarray的数据类型")

## ndarray数据类型的转换

通过 `astype` 转换ndarray的数据类型。


In [9]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [10]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
new_arr = numeric_strings.astype(float)

print(new_arr.dtype)
print(new_arr)

float64
[ 1.25 -9.6  42.  ]


# numpy数组的运算

- 数组很重要，因为它不用编写循环即可对数据执行批量运算，NumPy用户称其为向量化(vectorization)。大小相等的数组之间的任何算术运算都会将运算应用到元素级
- 数组与标量的算术运算会将标量值传播到数组中的各个元素
- 大小相同的数组之间的比较会生成布尔值数组
- 不同大小的数组之间的运算称为广播

In [11]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [12]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [14]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

# 比较操作
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

# numpy数组的切片和索引

如果你想得到ndarray切片的副本而非视图，就需要显式地复制数组，例如 `arr[5:8].copy()`

布尔型数组

In [15]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr3[5]

5

In [17]:
arr3[5:8]

array([5, 6, 7])

In [18]:
arr3[5:8] = 12
arr3

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [19]:
arr3_slice = arr3[5:8]

print(type(arr3_slice))

# arr3_slice = 10
arr3_slice[:] = 10
arr3

<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [20]:
# 布尔型数组

names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [21]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [22]:
bob_name = names == 'Bob'
bob_name

array([ True, False, False,  True, False, False, False])

In [23]:
data[bob_name]

array([[4, 7],
       [0, 0]])

In [24]:
data[bob_name, 1:]

array([[7],
       [0]])

In [25]:
data[bob_name, 1]

array([7, 0])

In [26]:
not_bob_name = ~bob_name
not_bob_name

array([False,  True,  True, False,  True,  True,  True])

In [27]:
data[not_bob_name]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [28]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [29]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])